# -*- coding: utf-8 -*-
"""Set1/Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RUfD8KirduAwM_FVeCLhkhvcpuJA8ZRw
"""

#task4
import pandas as pd
import matplotlib.pyplot as pyplot


     survey_data = pd.read_csv(/content/survey_results_public.csv, usecols=['ConvertedComp', 'CompTotal', 'SocialMedia'])

    
   df.dropna(inplace=True)
 # Get unique values of 'ConvertedComp' column
    column_values1 = df[['ConvertedComp']].values.ravel()
    unique_values1 = pd.unique(column_values1)

 # Get unique values of 'CompTotal' column
    column_values2 = df[['CompTotal']].values.ravel()
    unique_values2 = pd.unique(column_values2)
    df = df.astype({'ConvertedComp': 'int64', 'CompTotal': 'int64'})