# -*- coding: utf-8 -*-
"""Set1/Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QO0LoDijAqqFBwTD65dv1fqAzwNW9y3b
"""

#set1task1
import pandas as pd
import numpy as np

with open('train.tsv', 'rb') as my_data:
    df = pd.read_csv(my_data, names=['A', 'B', 'C', 'D', 'E', 'F'], sep='\t')
#calculating mean price
    mean_price = round(np.mean(df['A']), 0)
    print(mean_price)
 #opening file and write mean 
    file = open('out0.csv ', "w")
    file.write(str(mean_price))