# -*- coding: utf-8 -*-
"""Set1/Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kox9zbq6QWBhX8zakCdheAzUghAwT198
"""

import pandas as pd

with open('train.tsv', 'rb') as my_data, open('description.csv') as data_description:
    df = pd.read_csv(my_data, names=['A', 'B', 'C', 'D', 'E', 'F'], sep='\t')
    df2 = pd.read_csv(data_description)

    result = df.join(df2.set_index('liczba'), on='D')
    result.to_csv('out2.csv', header=False, sep='\t')